version: '3.8'

networks:
  kafka-network:
    driver: bridge

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    networks:
      - kafka-network
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    networks:
      - kafka-network
    ports:
      - "9092:9092"
      - "9999:9999"  # JMX monitoring port
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 1048576
      KAFKA_MESSAGE_MAX_BYTES: 1048576
      KAFKA_LOG_RETENTION_BYTES: 1073741824
      KAFKA_REPLICA_FETCH_MAX_BYTES: 1048576
      KAFKA_NUM_NETWORK_THREADS: 3
      KAFKA_NUM_IO_THREADS: 8
      KAFKA_MIN_INSYNC_REPLICAS: 2
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      JMX_PORT: 9999
      KAFKA_JMX_OPTS: >-
        -Dcom.sun.management.jmxremote
        -Dcom.sun.management.jmxremote.local.only=false
        -Dcom.sun.management.jmxremote.authenticate=false
        -Dcom.sun.management.jmxremote.ssl=false
        -Djava.rmi.server.hostname=kafka
    depends_on:
      - zookeeper

  kafka-cli:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-cli
    networks:
      - kafka-network
    entrypoint: tail -f /dev/null
    depends_on:
      - kafka

  akhq:
    image: tchiotludo/akhq
    container_name: akhq
    networks:
      - kafka-network
    ports:
      - "8081:8080"
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            local:
              properties:
                bootstrap.servers: "kafka:29092"
          security:
            default-group: admin
    depends_on:
      - kafka

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    networks:
      - kafka-network
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_RPC_ADDRESS: 0.0.0.0
      CASSANDRA_START_RPC: "true"